apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_NAME: "postgres"
  DB_USER: "neuroflow"
  DB_PASSWORD: "password"
  POSTGRES_PASSWORD: "password"
  DB_HOST: "database-service"
  DB_PORT: "5432"
  DJANGO_SECRET_KEY: "mysecretkey"
  DJANGO_DEBUG: "True"
