apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:13.4-alpine3.14
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: backend-secret
        volumeMounts:
        - mountPath: /opt/pgdata
          name: pgdata-volume
      volumes:
      - name: pgdata-volume
        persistentVolumeClaim:
          claimName: pgdata-pvc
