# Generated by Django 4.2.5 on 2023-09-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('due_date', '-created_at'), 'verbose_name_plural': 'todos'},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'todo_lists'},
        ),
        migrations.AlterModelTable(
            name='person',
            table='people',
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todos',
        ),
        migrations.AlterModelTable(
            name='todolist',
            table='todo_lists',
        ),
    ]
