# Generated by Django 4.2.5 on 2023-09-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todolist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='todos.address'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='notes',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
